var GAME_LEVELS = [

//level one
  ["                                                                              !!!!!!x                             ",
   "                                                                             !!!!!!!x                             ",
   "                                                                            !!!!!!!!x                             ",
   "                                                                           !!!!!!!!!x                             ",
   "                                                                          !!!!!!!!!!x                             ",
   "                          xxxxxxxxx                    o      o          !!!!!!!!!!!x                             ",
   "                          x!!!!!!!x                                      !!!!!!!!!!!x                             ",
   "                          x       x                                      !!!!!!!!!!!x                             ",
   "                          x       x                 xxxxxxxxxxx          !!!!!!!!!!!x                             ",
   "                          x       x                 x!!!!!!!!!x           !!!!!!!!!!x                             ",
   "xxxxxxxxxxxxxx            x   o   xxxxxxxxxx        x!!!!!!!!!x            !!!!!!!!!x                             ",
   "         o   x            x           !!!!!x        x         x               !!!!!!x                             ",
   "             xxxxxxxxxxxxxx                x        x         x                     x                             ",
   "             x!!!!!!   o                   xxxxx   xx         x                     x                             ",
   "             x!!!!                                            x                     x                             ",
   "             x!!                                    o         x                     x                             ",
   "     @       x!               x                               xxxxxxxx       =  t   x                             ",
   "                              x    xxxxxxxxxxxxxxxxxxx  o  xxxxxxxxxxxxxxxxxxxxxxxxxx                             ",
   "                              x o  x                 x     x                                                      ",
   "!                             x  o x                 x!!!!!x                                                      ",
   "!!                            x o  x                 x!!!!!x                                                      ",
   "!!!!!                         xxxxxx                 xxxxxxx                                                      ",
   "!!!!!!!!!                                                                                                         "],
   
   
   //level two
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxx!!x                                                                    !x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!    x!!x                           =                                        !x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!    x!!xxxxxxxxxx                                                           !x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!    xx!!!!!!!!!!xx                                                          !x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!     xxxxxxxxxx!!x                                                          !x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!              xx!x         x               x                          oo    !x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!               x!x         x               x                               !!x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!               xvx         x     o   o     x                  !!!!!!!!  !!!!xx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!                           xx      |      xx           !xxxxxxxxxxxxxx  xxxxx   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!                            xx!!!!!!!!!!!xx            v                        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                             xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx                                         ",
   "                                        xxxxxxxx     x                                                            ",
   "                                               x     x                                                            ",
   "                                                            o                                      |   o   |      ",
   "                                                              xxxxxx!!!!!!!xxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxx ",
   "                                               x     x                                                            ",
   "!              xxxxxxx          xxxxx          x     x                                                            ",
   "!             xx  o  xx         x   x          x     x                                                            ",
   "!            xx       xx        x o x          x     x                                 xxxxxx                     ",
   "!            x         x        x   x          x     x                                                            ",
   "!            x         x        x   x          x     x                                                            ",
   "!    @       x         x!!!!!!!xx   xx         x     x                                                   xxx      ",
   "!            x                       xx!!!!!!!!x     x!!!!!!!!!!!x        =                               t       ",
   "!            x                        xxxxxxxxxx     x!!!!!!!!!!!x                                                ",
   "!            x                    o                              x                     =                          ",
   "!                                                                x                                                ",
   "!                                                                x                                 =              ",
   "!                      x                                        ox                                                ",
   "!    =                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx                                                "],

   //level three
  ["                                     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxvxxxxxvxxxxxxxxxxxvxxxxxxx",
   "                                     xx!!!xxxxxxxxxxxxxxxxxxx                    x           x                ",
   "                                      x   x                     oooo             x           x                ",
   "                                      x   x   o                                  x                 x          ",
   "                                      x              =        xxxxvxxxxxxxx     xx                 x          ",
   "                                     xx   xx                 xx                 xx           x     x          ",
   "                                      x   xxxxxxxxxxxxxxxxxxxxx                 xx     o     x     x          ",
   "                                      x   x           x!               xxxxxxxxxxxxxxxxxxxxxxx     x          ",
   "                                      x         o     x!               x  o xxx                    x          ",
   "                                     xx   xx          x!               x     =                     x          ",
   "                                      x               x!            xxxx                           x          ",
   "                                      x   x           x!          xxxxxx                           x          ",
   "                                      x   x     =     x!            o        xxxxxxxxxxxxxxxxxxxxxxx          ",
   "                                     xx o xx          xxxxxxxxxxxxxxxxxxxxxxxxxxx                        =    ",
   "                                      x   x                                  xxv                              ",
   "                                      x                                      x        !!!!                    ",
   "                             xxxxxxxxxxxxxxx     o    x                      x        !!!v                    ",
   "                             xxxxxxxxxxxxxxx          x!!!!!!!!!!!!!!!       x                 xxxxxxxxxxxxxxx",
   "                             x   v      v  xxxxxxxxxxxxxxxxxxxxxxxxxxx       x                 x              ",
   "                             xx           xx!!!!!!!!!!!!!!!!!!!!!!!!!!       x       !!!       x              ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x                                  x       !!!       xxxxxxvxxxxxx  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!x           x                                  x       !!!                 t x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!x     o                                    xxxxx                             x  ",
   "  x                           x                                          x   x                             x  ",
   "  x                           xx          x              =               ! x x               =             x  ",
   "  x       =                               x     o       xxx              !                                 x  ",
   "  x                                       x                             |!         xxx                     x  ",
   "  x                           xx          x                             !!x       xxxxx          x         x  ",
   "  x                           x     o     x                             !!x        xxxxxxxxxxxxxxxx        x  ",
   "  x                           xxxxxxxxxxxxxxxx oo xxxxxx oo xxxxxx oo xxx xx             xxxxxxxxxxx       x  ",
   "  x      @               !!!!!x           xxxxx!!xxxxxxx!!!!x!!!!x!!!!xx   xx       o            o         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
   //You Win/Lose screen
  ["                                                                                                             "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
